<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $this->getChild("head"); ?>
</head>

<body>
  <div id="container">
<?php echo $this->getChild("header"); ?>
    <div id="content">
<?php echo $this->getChild("messages"); ?>
<?php echo $this->getChild("content"); ?>
    </div>
<?php echo $this->getChild("footer"); ?>
  </div>
</body>
</html>